// src/pages/establishment/EstablishmentMyPage.jsx
import React, { useMemo, useState } from "react";
import { Alert, Button, Container, Form, Spinner } from "react-bootstrap";
import { useNavigate } from "react-router-dom";
import Swal from "sweetalert2";
import GlobalNav from "../../components/GlobalNav";
import EstablishmentDashboard from "../../components/establishment/EstablishmentDashboard";
import useEstablishmentMy from "../../hooks/useEstablishmentMy";
import "../../components/establishment/EstablishmentDashboard.css";
import "./NexusCompanyCatalog.css";

export default function EstablishmentMyPage() {
  const navigate = useNavigate();
  const { establishments, isLoading, apiError, activateCatalog, deactivateCatalog, removeEstablishment } = useEstablishmentMy();
  const [query, setQuery] = useState(""); const [statusFilter, setStatusFilter] = useState("all"); const [appFilter, setAppFilter] = useState("all"); const [deletingId, setDeletingId] = useState(null); const [activatingId, setActivatingId] = useState(null);
  const apps = useMemo(() => { const map = new Map(); establishments.forEach((e) => { const source=e?.source_app; if(source?.id) map.set(String(source.id),source); }); return Array.from(map.values()).sort((a,b)=>String(a.name||a.slug||"").localeCompare(String(b.name||b.slug||""),"pt-BR")); }, [establishments]);
  const filtered = useMemo(() => { const normalized=query.trim().toLowerCase(); return establishments.filter((est)=>{ const matchesQuery=!normalized||[est.name,est.fantasy,est.city,est.uf,est?.source_app?.name,est?.source_app?.slug].filter(Boolean).some((v)=>String(v).toLowerCase().includes(normalized)); const matchesStatus=statusFilter==="all"||(statusFilter==="active"&&est.catalog_active)||(statusFilter==="available"&&!est.catalog_active); const matchesApp=appFilter==="all"||String(est?.source_app?.id||est.app_id)===appFilter; return matchesQuery&&matchesStatus&&matchesApp; }); },[establishments,query,statusFilter,appFilter]);
  const activeCount=establishments.filter((e)=>e.catalog_active).length; const availableCount=establishments.length-activeCount;
  const handleActivate=async(establishment)=>{const name=establishment.fantasy||establishment.name;const result=await Swal.fire({title:"Criar catálogo na Nexus?",html:`<strong>${name}</strong> já existe no ecossistema Peter Tecnet. A Nexus disponibilizará essa empresa usando o registro compartilhado, sem duplicar dados.`,icon:"question",showCancelButton:true,confirmButtonText:"Criar catálogo",cancelButtonText:"Cancelar"});if(!result.isConfirmed)return;try{setActivatingId(establishment.id);const catalog=await activateCatalog(establishment.id);await Swal.fire("Catálogo criado","A empresa agora está disponível na Nexus.","success");if(catalog?.slug)navigate(`/establishment/item/${catalog.slug}`);}catch(error){await Swal.fire("Não foi possível criar o catálogo",error?.response?.data?.message||"Tente novamente.","error");}finally{setActivatingId(null);}};
  const handleDelete=async(establishment)=>{const name=establishment.fantasy||establishment.name;const catalogId=establishment.catalog_establishment_id||establishment.id;const isImported=!establishment.native_to_application;const result=await Swal.fire({title:isImported?"Remover catálogo da Nexus?":"Excluir empresa?",html:isImported?`O catálogo de <strong>${name}</strong> será desvinculado da Nexus. O registro compartilhado continuará no ecossistema.`:`Você está prestes a excluir <strong>${name}</strong>.`,icon:"warning",showCancelButton:true,confirmButtonText:isImported?"Remover catálogo":"Sim, excluir empresa",cancelButtonText:"Cancelar"});if(!result.isConfirmed)return;try{setDeletingId(catalogId);if(isImported)await deactivateCatalog(establishment.id);else await removeEstablishment(catalogId);await Swal.fire(isImported?"Catálogo removido":"Empresa excluída","Operação concluída.","success");}catch(error){await Swal.fire("Não foi possível concluir",error?.response?.data?.message||"Tente novamente.","error");}finally{setDeletingId(null);}};
  return <><GlobalNav/><main className="company-hub"><Container fluid className="company-hub__container"><header className="company-hub__header"><div><span className="company-hub__eyebrow">Ecossistema Peter Tecnet</span><h1>Empresas e catálogos</h1><p>Todas as empresas vinculadas à sua conta aparecem aqui, independentemente do aplicativo em que foram cadastradas.</p></div><Button className="company-hub__new" onClick={()=>navigate("/establishment/create")}>Nova empresa</Button></header><section className="company-hub__summary"><div><strong>{establishments.length}</strong><span>empresas no ecossistema</span></div><div><strong>{activeCount}</strong><span>catálogos Nexus ativos</span></div><div><strong>{availableCount}</strong><span>podem criar catálogo</span></div></section><section className="company-hub__toolbar company-hub__toolbar--ecosystem"><div className="company-hub__search"><Form.Control value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Buscar empresa, cidade, UF ou aplicativo"/></div><Form.Select value={statusFilter} onChange={(e)=>setStatusFilter(e.target.value)}><option value="all">Todos os catálogos</option><option value="active">Catálogo ativo</option><option value="available">Sem catálogo Nexus</option></Form.Select><Form.Select value={appFilter} onChange={(e)=>setAppFilter(e.target.value)}><option value="all">Todos os aplicativos</option>{apps.map((app)=><option key={app.id} value={String(app.id)}>{app.name||app.slug}</option>)}</Form.Select></section>{isLoading&&<div className="company-hub__loading"><Spinner animation="border"/></div>}{!isLoading&&apiError&&<Alert variant="danger">{apiError}</Alert>}{!isLoading&&!apiError&&establishments.length===0&&<section className="company-hub__empty"><h2>Nenhuma empresa vinculada à sua conta</h2><p>Cadastre uma empresa em qualquer plataforma Peter Tecnet. O mesmo registro poderá ser reutilizado pelos aplicativos compatíveis.</p><Button onClick={()=>navigate("/establishment/create")}>Cadastrar empresa</Button></section>}{!isLoading&&!apiError&&establishments.length>0&&filtered.length===0&&<Alert variant="secondary">Nenhuma empresa corresponde aos filtros selecionados.</Alert>}{!isLoading&&!apiError&&filtered.length>0&&<section className="company-grid">{filtered.map((establishment)=>{const catalogId=establishment.catalog_establishment_id||establishment.id;return <EstablishmentDashboard key={establishment.id} establishment={establishment} navigate={navigate} deleting={Number(deletingId)===Number(catalogId)} activating={Number(activatingId)===Number(establishment.id)} onActivate={handleActivate} onDelete={()=>handleDelete(establishment)}/>;})}</section>}</Container></main></>;
}
